General:
    Measurement: "PHYSLITE_ATLAS_t_tbar"
    POI: "ttbar_norm"
    HistogramFolder: "histograms/"
    InputPath: "histograms.root:{SamplePath}"
    
Regions: 
  - Name: "mamin_region"
    # RegionPath: "SR"
    Variable: "$m_{bjj}$ [GeV]"
    Binning: [ 50.0, 70.0, 90.0, 110.0, 130.0, 150.0, 170.0, 190.0, 210.0, 230.0, 250.0, 270.0, 290.0, 310.0, 330.0, 350.0, 370.0, 390.0, 410.0, 430.0, 450.0, 470.0, 490.0, 510.0, 530.0, 550.0 ]

    
Samples:
  - Name: "Pseudodata"
    SamplePath: "pseudodata"
    Data: True      
    
  - Name: "1) single top s chan."
    SamplePath: "single top s chan."   
    
  - Name: "2) single top t chan."
    SamplePath: "single top t chan."
    
  - Name: "3) single top tW chan."
    SamplePath: "single top tW chan."    
    
  - Name: "4) $t \\bar{t}$"
    SamplePath: "$t \\bar{t}$"       
    
Systematics:
  - Name: "Luminosity"
    Up:
      Normalization: 0.05
    Down:
      Normalization: -0.05
    Type: "Normalization"    
    
    
NormFactors:
  - Name: "ttbar_norm"
    Samples: "4) $t \\bar{t}$"
    Nominal: 1.0
    Bounds: [0, 10]