General:
    Measurement: "PHYSLITE_ATLAS_t_tbar"
    POI: "ttbar_norm"
    HistogramFolder: "histograms/"
    InputPath: "histograms.root:{SamplePath}"
    VariationPath: ""
    
Regions: 
  - Name: "mamin_region"
    # RegionPath: "SR"
    Variable: "$m_{bjj}$ [GeV]"

    
Samples:
    -Name: "Pseudodata"
    SamplePath: "pseudodata"
    Data: True
    
    -Name: "Singletop_schan_lept_top"
    SamplePath: "singletop_schan_lept_top"
    
    -Name: "Singletop_schan_lept_antitop"
    SamplePath: "singletop_schan_lept_antitop"
    
    -Name: "t-chan_BW50_lept_top"
    SamplePath: "tchan_BW50_lept_top"
    
    -Name: "t-chan_BW50_lept_antitop"
    SamplePath: "tchan_BW50_lept_antitop"
    
    -Name: "t-W_dyn_DR_incl_antitop"
    SamplePath: "tW_dyn_DR_incl_antitop"
    
    -Name: "t-W_dyn_DR_incl_top"
    SamplePath: "tW_dyn_DR_incl_top"
    
    -Name: "t-tbar_hdamp258p75_nonallhad"
    SamplePath: "ttbar_hdamp258p75_nonallhad"
    
    
Systematics:
  - Name: "Luminosity"
    Up:
      Normalization: 0.05
    Down:
      Normalization: -0.05
    Type: "Normalization"    
    
    
NormFactors:
  - Name: "ttbar_norm"
    Samples: "ttbar_hdamp258p75_nonallhad"
    Nominal: 1.0
    Bounds: [0, 10]