General:
    Measurement: "PHYSLITE_ATLAS_t_tbar"
    POI: "ttbar_norm"
    HistogramFolder: "histograms/"
    InputPath: "histograms.root:{SamplePath}"
    VariationPath: ""
    
Regions: 
  - Name: "mamin_region"
    # RegionPath: "SR"
    Variable: "$m_{bjj}$ [GeV]"

    
Samples:
  - Name: "Pseudodata"
    SamplePath: "pseudodata"
    Data: True
    
  - Name: "single top s chan."
    SamplePath: "single top s chan."
    
  - Name: "single top t chan."
    SamplePath: "single top t chan."
    
  - Name: "single top tW chan."
    SamplePath: "single top tW chan."    
    
  - Name: "$t \\bar{t}$"
    SamplePath: "$t \\bar{t}$"
    
    
Systematics:
  - Name: "Luminosity"
    Up:
      Normalization: 0.05
    Down:
      Normalization: -0.05
    Type: "Normalization"    
    
    
NormFactors:
  - Name: "ttbar_norm"
    Samples: "$t \\bar{t}$"
    Nominal: 1.0
    Bounds: [0, 10]